/* confdefs.h */
#define PACKAGE_NAME "emopt"
#define PACKAGE_TARNAME "emopt"
#define PACKAGE_VERSION "version-0.5"
#define PACKAGE_STRING "emopt version-0.5"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_MPI_H 1
#define HAVE_BOOST_GEOMETRY_GEOMETRIES_POLYGON_HPP 1
